# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [3]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [10]:
# Your code here :
X = data.drop(columns='MEDV')
#print(X.head())
y = data['MEDV']
print(y.head())
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)



0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64
Train set: (404, 13) (404,)
Test set: (102, 13) (102,)


## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [13]:
# Your code here :
from sklearn.linear_model import LinearRegression
LR_model = LinearRegression()
LR_model.fit(X_train, y_train)
 
y_train_pred = LR_model.predict(X_train)
y_test_pred = LR_model.predict(X_test)


## 3. Calculate and print R-squared for both the training and the testing set.

In [20]:
# Your code here :
RSQ_train = LR_model.score(X_train, y_train)
RSQ_test = LR_model.score(X_test, y_test)
print(f"R2 score - train dataset: {RSQ_train}")
print(f"R2 score - test dataset: {RSQ_test}")


R2 score - train dataset: 0.7508856358979673
R2 score - test dataset: 0.6687594935356307


## 4. Calculate and print mean squared error for both the training and the testing set.

In [21]:
from sklearn.metrics import mean_squared_error

# Your code here :
mse_train = mean_squared_error(y_train, y_train_pred)
mse_test = mean_squared_error(y_test, y_test_pred)

print(f"Mean Squared Error - Train set: {mse_train}")
print(f"Mean Squared Error - Test set: {mse_test}")

Mean Squared Error - Train set: 21.641412753226312
Mean Squared Error - Test set: 24.291119474973613


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [22]:
from sklearn.metrics import mean_absolute_error

# Your code here :
# Calculate mean absolute error for both the training and the testing set
mae_train = mean_absolute_error(y_train, y_train_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)

print(f"Mean Absolute Error - Train set: {mae_train}")
print(f"Mean Absolute Error - Test set: {mae_test}")

Mean Absolute Error - Train set: 3.314771626783227
Mean Absolute Error - Test set: 3.189091965887852


## Classification Model Evaluation

In [40]:
from sklearn.datasets import load_iris
data = load_iris()


In [41]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [42]:
column_names = data.feature_names
column_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [44]:
df = pd.DataFrame(data['data'],columns=column_names)

In [45]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [46]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [47]:
target = pd.DataFrame(data.target)

In [48]:
data.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [49]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [50]:
# Your code here :
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( df, target, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)



Train set: (120, 4) (120, 1)
Test set: (30, 4) (30, 1)


## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [ ]:
# Your code here :
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear')
LR.fit(X_train,y_train)

y_train_pred = LR.predict(X_train)
y_train_pred_prob = LR.predict_proba(X_train)
#print(y_train_pred_prob)

y_test_pred = LR.predict(X_test)
y_test_pred_prob = LR.predict_proba(X_test)
#print(y_test_pred_prob)




[[0.17609878 0.38631752 0.4375837 ]
 [0.44663023 0.31821706 0.23515271]
 [0.09888236 0.40666114 0.4944565 ]
 [0.44148722 0.32331075 0.23520203]
 [0.23796653 0.3797081  0.38232537]
 [0.10893214 0.39278258 0.49828529]
 [0.10969239 0.40586828 0.48443932]
 [0.20446949 0.39065036 0.40488015]
 [0.17828715 0.39779221 0.42392064]
 [0.47024367 0.31060543 0.2191509 ]
 [0.09425006 0.40651872 0.49923122]
 [0.45578199 0.31705035 0.22716766]
 [0.20036671 0.39501347 0.40461982]
 [0.47756133 0.31071829 0.21172038]
 [0.10521238 0.39736527 0.49742235]
 [0.45687995 0.31442401 0.22869604]
 [0.51157302 0.29491291 0.19351407]
 [0.19911634 0.38686439 0.41401926]
 [0.17848987 0.39360154 0.42790859]
 [0.12306963 0.40001532 0.47691505]
 [0.46412102 0.31510271 0.22077627]
 [0.20821755 0.38965122 0.40213123]
 [0.06164361 0.40707439 0.53128201]
 [0.11567773 0.38926899 0.49505329]
 [0.19734932 0.39296624 0.40968445]
 [0.19927129 0.38772842 0.41300029]
 [0.43986661 0.3184495  0.24168389]
 [0.23922478 0.37831281 0.38

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [57]:
from sklearn.metrics import accuracy_score

# Your code here :
# Calculate accuracy score for both the training and the testing set
accuracy_train = accuracy_score(y_train, y_train_pred)
accuracy_test = accuracy_score(y_test, y_test_pred)

print(f"Accuracy Score - Train set: {accuracy_train}")
print(f"Accuracy Score - Test set: {accuracy_test}")




Accuracy Score - Train set: 0.6416666666666667
Accuracy Score - Test set: 0.8333333333333334


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [58]:
from sklearn.metrics import balanced_accuracy_score

# Calculate balanced accuracy score for both the training and the testing set
balanced_accuracy_train = balanced_accuracy_score(y_train, y_train_pred)
balanced_accuracy_test = balanced_accuracy_score(y_test, y_test_pred)

print(f"Balanced Accuracy Score - Train set: {balanced_accuracy_train}")
print(f"Balanced Accuracy Score - Test set: {balanced_accuracy_test}")

Balanced Accuracy Score - Train set: 0.6814814814814815
Balanced Accuracy Score - Test set: 0.6666666666666666


## 10. Calculate and print the precision score for both the training and the testing set.

In [59]:
from sklearn.metrics import precision_score

# Your code here :
# Calculate precision score for both the training and the testing set
precision_train = precision_score(y_train, y_train_pred, average='weighted')
precision_test = precision_score(y_test, y_test_pred, average='weighted')

print(f"Precision Score - Train set: {precision_train}")
print(f"Precision Score - Test set: {precision_test}")

Precision Score - Train set: 0.8250992063492063
Precision Score - Test set: 0.7261904761904762


## 11. Calculate and print the recall score for both the training and the testing set.

In [60]:
from sklearn.metrics import recall_score

# Your code here :
# Calculate recall score for both the training and the testing set
recall_train = recall_score(y_train, y_train_pred, average='weighted')
recall_test = recall_score(y_test, y_test_pred, average='weighted')

print(f"Recall Score - Train set: {recall_train}")
print(f"Recall Score - Test set: {recall_test}")

Recall Score - Train set: 0.6416666666666667
Recall Score - Test set: 0.8333333333333334


## 12. Calculate and print the F1 score for both the training and the testing set.

In [61]:
from sklearn.metrics import f1_score

# Your code here :
# Calculate F1 score for both the training and the testing set
f1_train = f1_score(y_train, y_train_pred, average='weighted')
f1_test = f1_score(y_test, y_test_pred, average='weighted')

print(f"F1 Score - Train set: {f1_train}")
print(f"F1 Score - Test set: {f1_test}")

F1 Score - Train set: 0.539381560283688
F1 Score - Test set: 0.7681159420289856


## 13. Generate confusion matrices for both the training and the testing set.

In [68]:
# Your code here :
import numpy as np
from sklearn.metrics import confusion_matrix
confusion_matrix_train = confusion_matrix(y_train, y_train_pred)
np.set_printoptions(precision=2)
print(f" Train Confusion Matrix: \n {confusion_matrix_train}")

confusion_matrix_test = confusion_matrix(y_test, y_test_pred)
np.set_printoptions(precision=2)
print(f" Test Confusion Matrix:\n {confusion_matrix_test}")


 Train Confusion Matrix: 
 [[34  0  0]
 [ 0  2 43]
 [ 0  0 41]]
 Test Confusion Matrix:
 [[16  0  0]
 [ 0  0  5]
 [ 0  0  9]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [95]:
# Have fun here !
##-------------Regression----------------#
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Load the dataset
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

#Split the dataset into X and y
X = data.drop(columns='MEDV')
#print(X.head())
y = data['MEDV']
#print(y.head())
# Instantiate a Lasso Regression model
lasso = linear_model.Lasso(alpha=0.1) # Create a Lasso regressor
lasso.fit(X_train, y_train) # Perform the fitting

# Predict the target variable for both the training and the testing set
y_train_pred_lasso = lasso.predict(X_train)
y_test_pred_lasso = lasso.predict(X_test)

# -----Evaluation-----#
# The mean squared error
test_mse_lasso = mean_squared_error(y_test, y_test_pred_lasso)
print('Test - Mean Squared Error:', test_mse_lasso)
train_mse_lasso = mean_squared_error(y_train, y_train_pred_lasso)
print('Train - Mean Squared Error:', train_mse_lasso)

# The mean absolute error
test_mae_lasso = mean_absolute_error(y_test, y_test_pred_lasso)
print('Test - Mean Absolute Error:', test_mae_lasso)
train_mae_lasso = mean_absolute_error(y_train, y_train_pred_lasso)
print('Train - Mean Absolute Error:', train_mae_lasso)

# The coefficient of determination: 1 is perfect prediction
r2score_lasso_train = r2_score(y_train, y_train_pred_lasso)
print('Train - R^2 Score: {}'.format(r2score_lasso_train))
r2score_lasso_test = r2_score(y_test, y_test_pred_lasso)
print('Test - R^2 Score: {}'.format(r2score_lasso_test))



Test - Mean Squared Error: 0.06508887643954048
Train - Mean Squared Error: 0.07133419057636878
Test - Mean Absolute Error: 0.19566485620242144
Train - Mean Absolute Error: 0.21602168118609907
Train - R^2 Score: 0.8852404933192146
Test - R^2 Score: 0.9164336821746271


In [82]:
# Have fun here !
##-------------Regression----------------#
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Load the dataset
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

#Split the dataset into X and y
X = data.drop(columns='MEDV')
#print(X.head())
y = data['MEDV']
#print(y.head())

#Split the dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

#Instantiate a Linear Regression model
from sklearn import linear_model 
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score, recall_score
ridge = linear_model.Ridge(alpha=1) # Create a Ridge regressor
ridge.fit(X_train, y_train) # Perform the fitting

#Predict the target variable for both the training and the testing set
y_train_pred_ridge = ridge.predict(X_train)
y_test_pred_ridge = ridge.predict(X_test)

# -----Evaluation-----#
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# The mean squared error
test_mse_ridge = mean_squared_error(y_test, y_test_pred_ridge)
print('Test - Mean Squared Error:', test_mse_ridge)
train_mse_ridge = mean_squared_error(y_train, y_train_pred_ridge)
print('Train - Mean Squared Error:', train_mse_ridge)

# The mean absolute error
test_mae_ridge = mean_absolute_error(y_test, y_test_pred_ridge)
print('Test - Mean Absolute Error:', test_mae_ridge)
train_mae_ridge = mean_absolute_error(y_train, y_train_pred_ridge)
print('Train - Mean Absolute Error:', train_mae_ridge)

# The coefficient of determination: 1 is perfect prediction
r2score_ridge_train = r2_score(y_train, y_train_pred_ridge)
print('Train - R^2 Score: {}'.format(r2score_ridge_train))
r2score_ridge_test = r2_score(y_test, y_test_pred_ridge)
print('Test - R^2 Score: {}'.format(r2score_ridge_test))



Train set: (404, 13) (404,)
Test set: (102, 13) (102,)
Test - Mean Squared Error: 24.47719122770868
Train - Mean Squared Error: 21.82411829157586
Test - Mean Absolute Error: 3.1329474278055365
Train - Mean Absolute Error: 3.3003067886850688
Train - R^2 Score: 0.7487825119234439
Test - R^2 Score: 0.6662221670168518


In [94]:
#-------------Classification----------------#
#Instantiate a Logistic Regression model
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np
#Load the dataset
from sklearn.datasets import load_iris
data = load_iris()
column_names = data.feature_names

# Set Input and Output VARIABLES
df = pd.DataFrame(data['data'],columns=column_names)
data['target_names']
target = pd.DataFrame(data.target, columns=['class'])

#Train and Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( df, target, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

#Instantiate the DecisionTreeClassifier
irisTree = DecisionTreeClassifier(criterion="log_loss", max_depth = 10)
#Fit the model with the training data
irisTree.fit(X_train,y_train)

#Predict the output of the testing data
predTree_test = irisTree.predict(X_test)
predTree_train = irisTree.predict(X_train)

#Print the output of the testing and training  data
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, predTree_test))
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_train, predTree_train))


# -----Evaluation-----#
# Calculate and print evaluation metrics
accuracy_train_dt = accuracy_score(y_train, predTree_train)
accuracy_test_dt = accuracy_score(y_test, predTree_test)
print(f"Decision Tree Accuracy Score - Train set: {accuracy_train_dt}")
print(f"Decision Tree Accuracy Score - Test set: {accuracy_test_dt}")

precision_train_dt = precision_score(y_train, predTree_train, average='weighted')
precision_test_dt = precision_score(y_test, predTree_test, average='weighted')
print(f"Decision Tree Precision Score - Train set: {precision_train_dt}")
print(f"Decision Tree Precision Score - Test set: {precision_test_dt}")

recall_train_dt = recall_score(y_train, predTree_train, average='weighted')
recall_test_dt = recall_score(y_test, predTree_test, average='weighted')
print(f"Decision Tree Recall Score - Train set: {recall_train_dt}")
print(f"Decision Tree Recall Score - Test set: {recall_test_dt}")

f1_train_dt = f1_score(y_train, predTree_train, average='weighted')
f1_test_dt = f1_score(y_test, predTree_test, average='weighted')
print(f"Decision Tree F1 Score - Train set: {f1_train_dt}")
print(f"Decision Tree F1 Score - Test set: {f1_test_dt}")

confusion_matrix_train_dt = confusion_matrix(y_train, predTree_train)
confusion_matrix_test_dt = confusion_matrix(y_test, predTree_test)
print(f"Decision Tree Train Confusion Matrix: \n {confusion_matrix_train_dt}")
print(f"Decision Tree Test Confusion Matrix:\n {confusion_matrix_test_dt}")


Train set: (120, 4) (120, 1)
Test set: (30, 4) (30, 1)
DecisionTrees's Accuracy:  0.9666666666666667
DecisionTrees's Accuracy:  1.0
Decision Tree Accuracy Score - Train set: 1.0
Decision Tree Accuracy Score - Test set: 0.9666666666666667
Decision Tree Precision Score - Train set: 1.0
Decision Tree Precision Score - Test set: 0.9700000000000001
Decision Tree Recall Score - Train set: 1.0
Decision Tree Recall Score - Test set: 0.9666666666666667
Decision Tree F1 Score - Train set: 1.0
Decision Tree F1 Score - Test set: 0.9656920077972709
Decision Tree Train Confusion Matrix: 
 [[34  0  0]
 [ 0 45  0]
 [ 0  0 41]]
Decision Tree Test Confusion Matrix:
 [[16  0  0]
 [ 0  4  1]
 [ 0  0  9]]


In [ ]:
#-------------Classification----------------#
#Instantiate a Logistic Regression model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np
#Load the dataset
from sklearn.datasets import load_iris
data = load_iris()
column_names = data.feature_names

# Set Input and Output VARIABLES
df = pd.DataFrame(data['data'],columns=column_names)
data['target_names']
target = pd.DataFrame(data.target, columns=['class'])

#Train and Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( df, target, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)


# Instantiate a RandomForestClassifier model
rf = RandomForestClassifier(n_estimators=100, random_state=4)
rf.fit(X_train, y_train.values.ravel())

# Predict the target variable for both the training and the testing set
y_train_pred_rf = rf.predict(X_train)
y_test_pred_rf = rf.predict(X_test)

# -----Evaluation-----#
# Calculate and print evaluation metrics
accuracy_train_rf = accuracy_score(y_train, y_train_pred_rf)
accuracy_test_rf = accuracy_score(y_test, y_test_pred_rf)
print(f"Random Forest Accuracy Score - Train set: {accuracy_train_rf}")
print(f"Random Forest Accuracy Score - Test set: {accuracy_test_rf}")

precision_train_rf = precision_score(y_train, y_train_pred_rf, average='weighted')
precision_test_rf = precision_score(y_test, y_test_pred_rf, average='weighted')
print(f"Random Forest Precision Score - Train set: {precision_train_rf}")
print(f"Random Forest Precision Score - Test set: {precision_test_rf}")

recall_train_rf = recall_score(y_train, y_train_pred_rf, average='weighted')
recall_test_rf = recall_score(y_test, y_test_pred_rf, average='weighted')
print(f"Random Forest Recall Score - Train set: {recall_train_rf}")
print(f"Random Forest Recall Score - Test set: {recall_test_rf}")

f1_train_rf = f1_score(y_train, y_train_pred_rf, average='weighted')
f1_test_rf = f1_score(y_test, y_test_pred_rf, average='weighted')
print(f"Random Forest F1 Score - Train set: {f1_train_rf}")
print(f"Random Forest F1 Score - Test set: {f1_test_rf}")

confusion_matrix_train_rf = confusion_matrix(y_train, y_train_pred_rf)
confusion_matrix_test_rf = confusion_matrix(y_test, y_test_pred_rf)
print(f"Random Forest Train Confusion Matrix: \n {confusion_matrix_train_rf}")
print(f"Random Forest Test Confusion Matrix:\n {confusion_matrix_test_rf}")


Train set: (120, 4) (120, 1)
Test set: (30, 4) (30, 1)
Random Forest Accuracy Score - Train set: 1.0
Random Forest Accuracy Score - Test set: 0.9666666666666667
Random Forest Precision Score - Train set: 1.0
Random Forest Precision Score - Test set: 0.9700000000000001
Random Forest Recall Score - Train set: 1.0
Random Forest Recall Score - Test set: 0.9666666666666667
Random Forest F1 Score - Train set: 1.0
Random Forest F1 Score - Test set: 0.9656920077972709
Random Forest Train Confusion Matrix: 
 [[34  0  0]
 [ 0 45  0]
 [ 0  0 41]]
Random Forest Test Confusion Matrix:
 [[16  0  0]
 [ 0  4  1]
 [ 0  0  9]]
